/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chattrabalho.clienteUI;

import chattrabalho.Mensagens.Exception.MensagemMuitoCurtaException;
import chattrabalho.Mensagens.Exception.MensagemMuitoGrandeException;
import chattrabalho.Mensagens.Mensagem;
import chattrabalho.Mensagens.MensagemEnviarMensagem;
import chattrabalho.Mensagens.MensagemTchau;
import chattrabalho.cliente.ClienteNegocios;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author pedro_000
 */
public class ClienteUI extends javax.swing.JFrame {
    
    final ClienteNegocios cliente;
    private final AtualizaConectados atualizaConectados  = new AtualizaConectados(this);
    private final AtualizaMensagens atualizaMensagens    = new AtualizaMensagens(this);
    private final Thread atualizaConectadosThread        = new Thread(atualizaConectados);
    private final Thread atualizaMensagensThread         = new Thread(atualizaMensagens);
    
    /**
     * Creates new form ClienteUI
     * @param c
    */
    public ClienteUI(ClienteNegocios c){
        initComponents();
        this.cliente = c; 
        this.atualizaConectadosThread.start();
        this.atualizaMensagensThread.start();
    }
    
    public void atualizaMensagens(){
        String Antigo = this.MensagensRecebidasUI.getText();
        String Novo   = this.cliente.retornaMensagemTratada();
        this.MensagensRecebidasUI.setText(Antigo + "\n" + Novo);
    }
    
    public ClienteNegocios retornaCliente(){
        return this.cliente;
    }
    
    public void adicionaMensagem(Mensagem mensagem){
        this.cliente.adicionaMensagem(mensagem);
    }
    
    public ArrayList retornaListaConectados(){
        return this.cliente.retornaListaConectados();
    }
    
    public void setaClientesConectados(String texto){
        this.ClientesConectadosUI.setText(texto);
    }
    
    public String retornaClientesConectados(){
        return this.ClientesConectadosUI.getText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MensagemEnviarUI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        IdentificadorUI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        EnviarMensagemBotao = new javax.swing.JButton();
        MensagensRecebidasUI = new javax.swing.JTextArea();
        ClientesConectadosUI = new javax.swing.JTextArea();
        TrocarApelidoBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mensagens Recebidas");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Clientes Conectados");

        MensagemEnviarUI.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mensagem a ser enviada");

        IdentificadorUI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IdentificadorUI.setText("0");
        IdentificadorUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdentificadorUIActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Identificador");

        EnviarMensagemBotao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        EnviarMensagemBotao.setText("Enviar Mensagem");
        EnviarMensagemBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarMensagemBotaoActionPerformed(evt);
            }
        });

        MensagensRecebidasUI.setEditable(false);
        MensagensRecebidasUI.setColumns(20);
        MensagensRecebidasUI.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        MensagensRecebidasUI.setRows(5);

        ClientesConectadosUI.setEditable(false);
        ClientesConectadosUI.setColumns(20);
        ClientesConectadosUI.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        ClientesConectadosUI.setRows(5);

        TrocarApelidoBotao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TrocarApelidoBotao.setText("Trocar apelido");
        TrocarApelidoBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrocarApelidoBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EnviarMensagemBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TrocarApelidoBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IdentificadorUI)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MensagemEnviarUI)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MensagensRecebidasUI, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                        .addGap(8, 8, 8)
                        .addComponent(ClientesConectadosUI, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MensagensRecebidasUI, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClientesConectadosUI, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MensagemEnviarUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdentificadorUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnviarMensagemBotao)
                    .addComponent(TrocarApelidoBotao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdentificadorUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdentificadorUIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdentificadorUIActionPerformed

    private void TrocarApelidoBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrocarApelidoBotaoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new TrocaApelido(this).setVisible(true);
    }//GEN-LAST:event_TrocarApelidoBotaoActionPerformed

    private void EnviarMensagemBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarMensagemBotaoActionPerformed
        // TODO add your handling code here:

        try {
            MensagemEnviarMensagem MEM = new MensagemEnviarMensagem(0,
                    Integer.parseInt(this.IdentificadorUI.getText()),
                    this.MensagemEnviarUI.getText());
            this.cliente.retornaBufferEnviar().adicionaMensagem(MEM);
            this.MensagemEnviarUI.setText("");
        } catch (MensagemMuitoGrandeException | MensagemMuitoCurtaException ex) {
            Logger.getLogger(ClienteUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_EnviarMensagemBotaoActionPerformed

    @SuppressWarnings("FinalizeCalledExplicitly")
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        System.out.println("Passou aqui?");
        setVisible(false);
        
        try {
            MensagemTchau tchau = new MensagemTchau();
            this.cliente.retornaBufferEnviar().adicionaMensagem(tchau);
        } catch (MensagemMuitoGrandeException | MensagemMuitoCurtaException ex) {
            System.out.println("Deu erro no finalize da janela");
        }
        
        System.gc();
        try {
            sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(ClienteUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        while(true){
            if (this.cliente == null){
                try {
                    this.finalize();
                } catch (Throwable ex) {
                    Logger.getLogger(ClienteUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
        
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ClientesConectadosUI;
    private javax.swing.JButton EnviarMensagemBotao;
    private javax.swing.JTextField IdentificadorUI;
    private javax.swing.JTextField MensagemEnviarUI;
    private javax.swing.JTextArea MensagensRecebidasUI;
    private javax.swing.JButton TrocarApelidoBotao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
